<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ClassIsland.Automation.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="ClassIsland.Shared.IPC" Version="2.0.4" />
    <PackageReference Include="ClassIsland.Shared" Version="2.0.4" />
  </ItemGroup>

</Project>
