<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Configurations>Debug;Release</Configurations>
    <RootNamespace>ClassIsland.Automation.V1</RootNamespace>
    <AssemblyName>ClassIsland.Automation.V1</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClassIsland.PluginSdk" Version="1.7.0">
      <ExcludeAssets>runtime; native</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="System.Text.Json" Version="8.0.5">
      <ExcludeAssets>runtime; native</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="QRCoder" Version="1.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassIsland.Automation.Core\ClassIsland.Automation.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="manifest.yml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="README.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
